SUBDIRS=Salto SpectralDelay
PROGRAMS=\
	SnapshotExample\
	Spectrum_example\
	FFT_example\
	FDFilterExample\
	ProcessingObject_controls_example\
	StereoToMonoFile\
	POCompositeExample\
	AudioIOExample\
	MIDI_Synthesizer_example\
	AudioApplicationExample\
	GUIAudioApplicationExample\
	FundamentalDetect\


TOP=..

include $(TOP)/unix_tools/make.rules
