SUBDIRS=Salto SpectralDelay 
PROGRAMS=\
	Spectrum_example\
	FFT_example\
	FDFilterExample\
	ProcessingObject_controls_example\
	StereoToMonoFile\
	POCompositeExample\
	AudioIOExample\
	MIDI_Synthesizer_example\
	AudioApplicationExample\
	GUIAudioApplicationExample\
	FundamentalDetect\
	XMLViewExample\
	SIViewExample\
	SnapshotExample


TOP=..

include $(TOP)/unix_tools/make.rules
