// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "SMSAnalysisTDD_Prototype.h"

Fl_Window* SMS_AnalysisTaskDefinition::BuildContents() {
  Fl_Window* w;
  { Fl_Window* o = mDialogWindow = new Fl_Window(665, 419, "New SMS Analysis task");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = mActionButtonsContainer = new Fl_Group(0, 380, 665, 40);
      o->color(50);
      { Fl_Button* o = mProceedAction = new Fl_Button(0, 390, 260, 25, "I am finished with defining this SMS Analysis");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(12);
      }
      { Fl_Button* o = mCancelAction = new Fl_Button(265, 390, 271, 25, "I no longer want to define a new SMS Analysis");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(12);
      }
      { Fl_Button* o = mHelpRequestedAction = new Fl_Button(540, 390, 125, 25, "I need help");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(12);
      }
      o->end();
    }
    { Fl_Tabs* o = mParamFamiliesTabs = new Fl_Tabs(0, 0, 665, 380);
      o->end();
    }
    o->end();
  }
  return w;
}
