.TH Voice2MIDI 1 "August 24, 2005" "version 0.1.2" "User Commands"
.SH NAME
Voice2MIDI \- Converts single voice audio into midi files
.SH SYNOPSIS
.B Voice2MIDI
.SH DESCRIPTION
This tool allows to convert digital audio containing a monophonic melody
into a midi file.
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO

