LIBRARIES=CLAM
SUBDIRS = src externals examples test
TOP=$(shell pwd)
CLEANFILES=unix_tools/*~
DISTCLEANFILES=unix_tools/configure\
               unix_tools/config.status\
               unix_tools/config.log\
               unix_tools/make.rules\
               unix_tools/modules/Storage.modules

include $(TOP)/unix_tools/make.rules

