/*
 * V2MIconData.hxx
 * Data for application icons.
 *
 * Ismael Mosquera Rivera PFC Voice2MIDI UPF 2004
*/
#ifndef _V2MICONDATA_
#define _V2MICONDATA_

static const char* const icon_data[] = { 
"32 32 148 2",
"ar c #000000",
".s c #151515",
".G c #191919",
".x c #1c1c1c",
".1 c #1f1f1f",
".S c #262626",
".R c #292929",
".k c #2a2a2a",
"#0 c #303030",
".j c #363636",
"#Z c #373737",
".r c #383838",
"#N c #3d3d3d",
"#O c #3e3e3e",
".i c #4d4d4d",
"#1 c #4e4e4e",
".q c #4f4f4f",
"#M c #505050",
".F c #515151",
"#K c #525252",
"#L c #565656",
".w c #575757",
"#2 c #595959",
"#b c #5c5c5c",
".h c #5d5d5d",
".y c #606060",
".g c #6b6b6b",
"#J c #6e6e6e",
"#m c #7b7b7b",
".c c #7f7f7f",
".t c #818181",
".f c #828282",
"ae c #868686",
"ad c #888888",
".d c #8a8a8a",
"ah c #8d8d8d",
".b c #909090",
"af c #919191",
"ag c #939393",
"ac c #999999",
"#y c #9a9a9a",
".0 c #9b9b9b",
".m c #9f9f9f",
".H c #a0a0a0",
"#I c #a4a4a4",
"#Y c #a6a6a6",
"ab c #a9a9a9",
"#t c #aa3838",
"#4 c #aa3e3e",
"ap c #ad2525",
"a. c #ae2b2b",
".n c #afafaf",
"#w c #b0b0b0",
"#c c #b1b1b1",
".a c #b3b3b3",
"ak c #b74343",
".p c #bfbfbf",
"#X c #c13333",
"#u c #c18181",
".u c #c1c1c1",
"#j c #c24040",
"#H c #c46262",
"#8 c #c48a8a",
"ai c #c5c5c5",
"#q c #c66c6c",
"#G c #c76a6a",
"#p c #c85555",
"am c #ca3232",
"aq c #cda8a8",
"#C c #ce8d8d",
"#f c #d04c4c",
"#V c #d06969",
".2 c #d0d0d0",
".M c #d14040",
"#s c #d29595",
"#7 c #d34c4c",
".Q c #d3d3d3",
".P c #d44b4b",
".o c #d5d5d5",
"#Q c #d65f5f",
"#k c #d6afaf",
".Y c #d75757",
".v c #d7d7d7",
".Z c #d96363",
"#R c #dccfcf",
"#g c #ddb8b8",
"aj c #de8383",
"a# c #e0d2d2",
"an c #e1d4d4",
".9 c #e25656",
".O c #e28787",
"#S c #e2d7d7",
"#W c #e3a8a8",
"#E c #e46e6e",
"#i c #e47474",
".5 c #e55e5e",
"#l c #e59393",
"#T c #e65151",
"#F c #e6d6d6",
"#x c #e6e6e6",
"#B c #e7b7b7",
"#9 c #e7c7c7",
"#U c #e88181",
".A c #e89f9f",
"#3 c #e9bebe",
".E c #e9e9e9",
"al c #ea9090",
"## c #ebabab",
".X c #ed5959",
"#6 c #ed6464",
"ao c #ede4e4",
"#a c #ededed",
"#r c #ee7676",
".N c #eeb7b7",
"#. c #f0dede",
".V c #f19c9c",
"#5 c #f1f0f0",
".l c #f1f1f1",
"#z c #f2f2f2",
".8 c #f37979",
"#e c #f38282",
"#o c #f3a5a5",
".z c #f3cfcf",
"aa c #f4f4f4",
"#D c #f5d7d7",
".W c #f68080",
".C c #f6dbdb",
"#A c #f76d6d",
".4 c #f78484",
"#h c #f7abab",
".L c #f8caca",
".e c #f8f8f8",
".U c #f98f8f",
".D c #f9e7e7",
".7 c #fbdcdc",
".J c #fbe4e4",
"#P c #fbe7e7",
".6 c #fbf9f9",
".I c #fccbcb",
".K c #fcd4d4",
".B c #fcf3f3",
".# c #fdfdfd",
"#v c #fefefe",
"#n c #ff9393",
"#d c #ffb8b8",
".3 c #ffdada",
".T c #fff0f0",
"Qt c #ffffff",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt.#.a.b.c.d.eQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.#.f.g.h.i.j.k.lQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.m.n.o.p.q.r.s.tQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.uQtQtQt.v.w.x.yQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.z.A.BQtQtQt.C.A.DQtQtQtQt.E.F.G.HQtQt.I.JQtQtQt.K.LQtQtQtQt",
"QtQt.z.M.NQtQtQt.O.P.BQtQtQtQt.Q.R.SQtQt.T.U.VQtQtQt.W.XQtQtQtQt",
"QtQtQt.Y.ZQtQt.B.M.OQtQtQtQtQt.0.1.2QtQt.3.4.5.6Qt.7.8.9#.QtQtQt",
"QtQtQt##.M.CQt##.M.CQtQtQtQt#a#b#cQtQtQt#d#e#f#gQt#h#i#j#kQtQtQt",
"QtQtQt.B.M#lQt.Z.ZQtQtQtQt.##m.uQtQtQtQt#n#o#p#qQt#r#s#t#uQtQtQt",
"QtQtQtQt.O.P.C.M.NQtQtQt#v#w#xQtQtQt#y#z#A#B#C.M#D#E#F#G#HQtQtQt",
"QtQtQtQt.z.M.Y.P.BQtQtQt#I#J#K#L#M#N#O#P#Q#R#S#T#U#VQt#W#XQtQtQt",
"QtQtQtQtQt.Y.M.OQtQtQt#Y.h#Z#0#1.q.j#2#3#4#5Qt#6#7#8Qt#9a.a#QtQt",
"QtQtQtQtQt.A.M.zQtQtaaabacadaeafagahaiajakQtQtalamanQtaoapaqQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"arararararararararararararararQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"arararararararararararararararararararararararararararararararar",
"arararararararararararararararQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"arararararararararararararararQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"arararararararararararararararararararararararararararararararar",
"arararararararararararararararQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"arararararararararararararararQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"arararararararararararararararararararararararararararararararar",
"arararararararararararararararQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const icon_back_data[] = { 
"16 16 5 1",
". c None",
"# c #000000",
"c c #808080",
"b c #c0c0c0",
"a c #ffffff",
"................",
".......#........",
"......##........",
".....#a#........",
"....#aa########.",
"...#aabaaaaaaa#.",
"..#aabbbbbbbbb#.",
"...#abbbbbbbbb#.",
"...c#ab########.",
"....c#a#ccccccc.",
".....c##c.......",
"......c#c.......",
".......cc.......",
"........c.......",
"................",
"................"};

static const char* const icon_forward_data[] = { 
"16 16 5 1",
". c None",
"# c #000000",
"c c #808080",
"b c #c0c0c0",
"a c #ffffff",
"................",
"................",
".........#......",
".........##.....",
".........#a#....",
"..########aa#...",
"..#aaaaaaabaa#..",
"..#bbbbbbbbbaa#.",
"..#bbbbbbbbba#..",
"..########ba#c..",
"..ccccccc#a#c...",
"........c##c....",
"........c#c.....",
"........cc......",
"........c.......",
"................"};

static const char* const icon_home_data[] = { 
"16 16 4 1",
". c None",
"# c #000000",
"b c #c0c0c0",
"a c #ffffff",
"...........#....",
"###....##.......",
"..#...####......",
"..#..#aabb#.....",
"..#.#aaaabb#....",
"..##aaaaaabb#...",
"..#aaaaaaaabb#..",
".#aaaaaaaaabbb#.",
"###aaaaaaaabb###",
"..#aaaaaaaabb#..",
"..#aaa###aabb#..",
"..#aaa#.#aabb#..",
"..#aaa#.#aabb#..",
"..#aaa#.#aabb#..",
"..#aaa#.#aabb#..",
"..#####.######.."};

static const char* const icon_help_data[] = { 
"32 32 17 1",
"e c #000000",
"g c #0f0f0f",
"n c #1f1f1f",
"h c #2f2f2f",
"i c #3f3f3f",
"o c #4f4f4f",
"d c #5f5f5f",
"j c #6f6f6f",
"b c #7f7f7f",
"l c #8f8f8f",
"k c #9f9f9f",
"a c #afafaf",
"m c #bfbfbf",
"f c #cfcfcf",
"c c #dfdfdf",
"# c #efefef",
". c #ffffff",
"................................",
"................................",
"............#abbba#.............",
"..........cdeeeeeeed#...........",
".........fgeeeeeeeeeh#..........",
"........fgeeeeeeeeeeeh..........",
"........ieeeegjbdeeeeek.........",
".......feeeeh#...fgeeei.........",
".......leeeem.....jeeee.........",
".......kiiii......beeee.........",
".................#neeen.........",
"................#heeeej.........",
"...............#heeeegc.........",
"..............#heeeeek..........",
"..............oeeeeek...........",
".............meeeeek............",
".............oeeeel.............",
".............eeeeh..............",
"............feeeeb..............",
"............meeeea..............",
"............fiiiif..............",
"................................",
"................................",
".............foia...............",
"............cgeeea..............",
"............beeeei..............",
"............leeeeo..............",
"............#heegf..............",
".............#lbc...............",
"................................",
"................................",
"................................"};

#endif

