.TH SMSConsole 1 "August 24, 2005" "version 0.1.2" "User Commands"
.SH NAME
SMSConsole \- interactive console application featuring SMS analysis, synthesis and transformation
.SH SYNOPSIS
.B SMSConsole
.SH DESCRIPTION
Here goes SMSTools description
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
SMSTools(1), SMSBatch(1), QtSMSTools(1)
