.TH NetworkEditor 1 "August 24, 2005" "version 0.1.2" "User Commands"
.SH NAME
NetworkEditor \- Edits CLAM networks
.SH SYNOPSIS
.B NetworkEditor [Network.xml]
.SH DESCRIPTION
The NetworkEditor is a tool to edit CLAM networks. 
Those networks can be played from the same tool or from a Qt designer
interface using the Prototyper and the CLAM Qt Widgets plugin.
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
Prototyper(1), designer-qt4(1), QtSMSTools(1), Annotator(1) 
.PP
http://clam-project.org/wiki/Network_Editor_tutorial
(Network Editor Tutorial)

