PROGRAMS = \
	TestFl_SinTracks \
	TestAudioView \
	TestSpectrumView \
	TestSpectralPeakArrayView \
	TestSinTracksView \
	TestFl_Audio \
	TestFl_Spectrum \
	TestFl_SpectrumPeaks \
	SegmentTest \
	TestMIDIIO \
	TestAudioIO \
	TestControlMapper \
	AudioPlayer \
	TestPOComposite \
	TestAudioFileIO \
	TestSnapshots \



TESTS = \
	TestXMLAdapters \
	TestConfig \
	TestSignalv1 \
	TestArray \
	TestArray2 \
	TestDynamicType3 \
	TestError \
	TestFDFilterGen \
	TestFFT \
	TestIFFT \
	TestSpectrum \
	TestSpectrumAdder \
	TestWindowing \
	PhantomBufferTest \
	TestStreamRegions \
	TestStreamBuffer \
	TestEnvelopeExtractor \
	TestWaveGenerator \
	TestSpectrumAdder2 \
	TestSpectrumProduct \
	BPFTest \
	ListTest \

TOP=..

INCLUDE_DIRS+=$(CLAM_PATH)/test/testingWithCppUnit
INCLUDE_DIRS+=$(CLAM_PATH)/test/testingWithCppUnit/CommonHelpers

CLEANFILES=*.data

include $(TOP)/unix_tools/make.rules
