PROGRAMS = \
           TestSnapshots \
           TestEnum \
           TestComplex \
           TestPoint \
           TestPolar \
           BPFTest \
           ListTest \
           TestAudioFileIO \
           TestMIDIIO \
           TestAudioIO \
           TestControlMapper \
           TestControls \
           AudioPlayer \
           TestPOComposite \
           SegmentTest \

TESTS = \
        TestXMLAdapters \
        TestConfig \
        TestFlags \
        TestArray \
        TestArray2 \
        TestDynamicType3 \
        TestError \
        TestFDFilterGen \
        TestFFT \
        TestIFFT \
        TestSpectrum \
        TestSpectrumAdder \
        TestSpectrumAdder2 \
        TestSpectrumProduct \
        TestWindowing \
        PhantomBufferTest \
        TestStreamRegions \
        TestStreamBuffer \
        TestEnvelopeExtractor \
        TestWaveGenerator \

TOP=..

CLEANFILES=*.data

include $(TOP)/unix_tools/make.rules
