.TH Annotator 1 "August 24, 2005" "version 0.3.0" "MISCELLANEOUS"
.SH NAME
Annotator \- CLAM Music Annotator
.SH SYNOPSIS
.B Annotator [<ProjectFile.pro>]
.SH DESCRIPTION
This is a graphical tool that allows to visualize and edit annotations over 
music files.
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
ClamExtractorExample(1)
