.TH SMSConsole 9 "August 24, 2005" "version 0.1.2" "MISCELLANEOUS"
.SH NAME
SMSConsole \- graphical application featuring SMS analysis, synthesis and transformation
.SH SYNOPSIS
.B SMSConsole
.SH DESCRIPTION
Here goes SMSTools description
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
SMSTools(9), SMSBatch(9)
