import sys, os

sys.path+=['../libs']
from buildtools import *
# CLAM unit tests build

tests_env = Environment( ENV=os.environ )
Export( 'tests_env' )

opts = Options('unit_tests.conf')
opts.Add( PathOption( 'clam_prefix', 'Prefix were CLAM was installed', '/usr') )
opts.Update(tests_env)
opts.Save('unit_tests.conf', tests_env)
Help(opts.GenerateHelpText(tests_env))

tests_env.Append( LIBS=['cppunit','dl'] )
tests_env.Append( CCFLAGS=['-O2','-Wall'] )

# read flags from pkg-config clam library descriptors

tests_env.ParseConfig( 'pkg-config --cflags --libs clam_core clam_processing clam_audioio')

SConscript('unit_tests/SConscript')
SConscript('functional_tests/SConscript')

Alias( 'all', ['run_unit_tests','run_functional_tests'] )
