// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef SMSAnalysisTDD_Prototype_h
#define SMSAnalysisTDD_Prototype_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Tabs.H>

class SMS_AnalysisTaskDefinition {
public:
  Fl_Window* BuildContents();
  Fl_Window *mDialogWindow;
  Fl_Group *mActionButtonsContainer;
  Fl_Button *mProceedAction;
  Fl_Button *mCancelAction;
  Fl_Button *mHelpRequestedAction;
  Fl_Tabs *mParamFamiliesTabs;
};
#endif
