#!/usr/bin/python
from clam_build_helpers import *

module = 'core'
Import(module+'_env version install_dirs crosscompiling')
env=core_env
moduleDependencies = []

folders = [
	'src/core',
	'src/core/base',
	'src/core/standard',
	'src/core/storage',
	'src/core/processing',
	'src/core/ports',
	'src/core/controls',
	'src/core/sinksources',
	'src/core/data',

	'src/Data/Descriptors/Pool',
	'src/Data/Editable',
	'src/Defines',
	'src/Errors',
	'src/Flow/Networks',
	'src/Processing/Plugins',
	'src/System',
	'src/System/Threads',
	'externals/CbLib',
	]

blacklist = [
	]

if sys.platform == 'win32' or crosscompiling :
	folders.append('src/Defines/Windows')

if env['xmlbackend'] == 'xercesc' :
	blacklist.append( 'LibXml.+')
	blacklist.append( 'NullDom.+' )
elif env['xmlbackend'] == 'xmlpp' :
	blacklist.append( 'Xerces.+')
	blacklist.append( 'NullDom.+' )
elif env['xmlbackend'] == 'none' :
	blacklist.append( 'Xerces.+' )
	blacklist.append( 'LibXml.+' )

if not env.has_key('with_ladspa') or env['with_ladspa'] == False :
	blacklist.append( 'Ladspa.+' )
	blacklist.append( 'RunTimeFaustLibraryLoader.+' )
	blacklist.append( 'RunTimeLadspaLibraryLoader.*' )

lib_tgt, install_tgt = lib_rules( module, version, folders, blacklist, install_dirs, env, moduleDependencies)
Return( 'lib_tgt', 'install_tgt' )

