#include "EWindowType.hxx"

using namespace MTG;

MTG::Enum::tEnumValue EWindowType::sEnumValues[] = {
	{EWindowType::HAMMING,"HAMMING"},
	{EWindowType::KAISERBESSEL17,"KAISERBESSEL17"},
	{EWindowType::KAISERBESSEL18,"KAISERBESSEL18"},
	{EWindowType::KAISERBESSEL19,"KAISERBESSEL19"},
	{EWindowType::KAISERBESSEL20,"KAISERBESSEL20"},
	{EWindowType::KAISERBESSEL25,"KAISERBESSEL25"},
	{EWindowType::KAISERBESSEL30,"KAISERBESSEL30"},
	{EWindowType::KAISERBESSEL35,"KAISERBESSEL35"},
	{EWindowType::BLACKMAN_HARRIS_62,"BLACKMAN_HARRIS_62"},
	{EWindowType::BLACKMAN_HARRIS_70,"BLACKMAN_HARRIS_70"},
	{EWindowType::BLACKMAN_HARRIS_74,"BLACKMAN_HARRIS_74"},
	{EWindowType::BLACKMAN_HARRIS_92,"BLACKMAN_HARRIS_92"},
	{EWindowType::TRIANGULAR,"TRIANGULAR"},
	{EWindowType::CONSTANT_1,"CONSTANT_1"},
	{0,NULL}
};

MTG::Enum::tValue EWindowType::sDefault = EWindowType::HAMMING;
