#!/usr/bin/python

from PyQt4 import QtGui, QtCore
from PyQt4 import uic
import sys
import ipyclam

class ipyclam_controller(QtGui.QWidget):
	def __init__(self):
		super(ipyclam_controller, self).__init__()
		self.createNetwork()

		grid = QtGui.QGridLayout()
		button = QtGui.QPushButton("Play")
		self.connect(button, QtCore.SIGNAL('clicked()'), self.play)
		grid.addWidget(button, 0, 0)

		button = QtGui.QPushButton("Pause")
		self.connect(button, QtCore.SIGNAL('clicked()'), self.pause)
		grid.addWidget(button, 0, 1)

		button = QtGui.QPushButton("Stop")
		self.connect(button, QtCore.SIGNAL('clicked()'), self.stop)
		grid.addWidget(button, 0, 2)

		button = QtGui.QPushButton("Code")
		self.connect(button, QtCore.SIGNAL('clicked()'), self.showCode)
		grid.addWidget(button, 1, 0)

		button = QtGui.QPushButton("Configuration")
		self.connect(button, QtCore.SIGNAL('clicked()'), self.configure)
		grid.addWidget(button, 1, 1)

		self.setLayout(grid)

	def createNetwork(self):
		self._network = ipyclam.Network( ipyclam.Clam_NetworkProxy() )
		self._network.backend = "JACK"
		# Processings
		self._network.source = "AudioSource"
		self._network.sink = "AudioSink"
		self._network.smsanalysis = "SMSAnalysisCore"
		self._network.smssinusoidalgain = "SMSSinusoidalGain"
		self._network.smsresidualgain = "SMSResidualGain"
		self._network.smsfreqshift = "SMSFreqShift"
		self._network.synthesizer = "SMSSynthesis"
		self._network.outcontrolsender = "OutControlSender"
		self._network.outcontrolsender._config.ControlRepresentation = 1000
		# Connections
		self._network.source > self._network.smsanalysis
		self._network.smsanalysis["Sinusoidal Peaks"] > self._network.smssinusoidalgain["In SpectralPeaks"]
		self._network.smsanalysis > self._network.smsresidualgain
		self._network.smssinusoidalgain > self._network.smsfreqshift
		self._network.smsfreqshift > self._network.synthesizer
		self._network.smsresidualgain > self._network.synthesizer
		self._network.synthesizer.OutputAudio > self._network.sink["1"]
		self._network.outcontrolsender > self._network.smsfreqshift

	def showCode(self):
		QtGui.QMessageBox.about(self, "Code to build the network", self._network.code())

	def printCode(self):
		print self._network.code()

	def play(self):
		self._network.play()
		print 'Playing...'

	def pause(self):
		self._network.pause()
		print 'Paused'

	def stop(self):
		self._network.stop()
		print 'Stopped'

	def configure(self):
		self.ui = uic.loadUi("SMSmess.ui")
		self._network.bindUI(self.ui)
		self.ui.show()

if __name__ == "__main__" :
	app = QtGui.QApplication(sys.argv)
	w = ipyclam_controller()
	w.show()
	app.exec_()
