import os, sys

options_filename = 'options.cache'
opts = Options(options_filename,ARGUMENTS)
#TODO: fix default values
opts.Add(PathOption('prefix', 'The prefix where the CLAM library is installed', '/usr/local'))
#opts.Add(PathOption('plugins_prefix', 'The prefix where the CLAM plugins are installed', ''))
env = Environment(ENV=os.environ, options=opts)
Help(opts.GenerateHelpText(env))

avoid_configure_option=ARGUMENTS.get('force_avoid_configure',0)
needs_configure = ('configure' in COMMAND_LINE_TARGETS) or not os.path.exists(options_filename) or len(ARGUMENTS)>0
avoid_configure = '--help' in COMMAND_LINE_TARGETS or avoid_configure_option=='1' or avoid_configure_option=='yes' or '-c' in ARGUMENTS

if needs_configure and not avoid_configure :
	print 'Configure phase...'
	opts.Update(env)
	opts.Save(options_filename, env)
	print "Finished. Invoke 'scons' now."
	Exit(0)


env.Append( CPPPATH=[env['prefix']+'/include'] )
env.Append( LIBS=['clam_core','clam_audioio','clam_processing'] )
env.Append( LIBPATH=[env['prefix']+'/lib'] )
env.Append( CPPDEFINES=["USE_SNDFILE=1"] )

env.Append( CPPPATH=['/usr/include/python2.5','/usr/include/'] )
env.Append( LIBS=['boost_python'] )
env.Append( LIBPATH=['/usr/lib/python2.5/config'] )

#env.Append( CCFLAGS=['-g','-O3','-Wall'] )

env.SharedLibrary( target='clam', source=['clam_bindings.cxx','Definitions.cxx','indexing/indexing_slice.cpp','indexing/python_iterator.cpp'], SHLIBPREFIX='' )
