import os, sys

opts = Options('options.cache')
opts.Add(PathOption('prefix', 'The prefix where the CLAM library is installed', '/usr/local'))
env = Environment(ENV=os.environ, options=opts)
Help(opts.GenerateHelpText(env))

env.Append( CPPPATH=[env['prefix']+'/include'] )
env.Append( LIBS=['clam_core','clam_audioio','clam_processing'] )
env.Append( LIBPATH=[env['prefix']+'/lib'] )
env.Append( CPPDEFINES=["USE_SNDFILE=1"] )

env.Append( CPPPATH=['/usr/include/python2.5','/usr/include/'] )
env.Append( LIBS=['boost_python'] )
env.Append( LIBPATH=['/usr/lib/python2.5/config'] )

env.Append( CCFLAGS=['-g','-O3','-Wall'] )

env.SharedLibrary( target='clam', source=['clam_bindings.cxx','Definitions.cxx','indexing/indexing_slice.cpp','indexing/python_iterator.cpp'], SHLIBPREFIX='' )
