.TH SMSTools 1 "August 24, 2005" "version 0.1.2" "User Commands"
.SH NAME
SMSTools \- fltk based interface for SMS analysis, synthesis and transformation
.SH SYNOPSIS
.B SMSTools
.SH DESCRIPTION
Here goes SMSTools description
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
SMSConsole(1), SMSBatch(1), QtSMSTools(1)
