.TH QtSMSTools 1 "August 24, 2005" "version 0.1.2" "User Commands"
.SH NAME
QtSMSTools \- qt based interface for SMS analysis, synthesis and transformation
.SH SYNOPSIS
.B QtSMSTools
.SH DESCRIPTION
The Qt port of SMSTools based on fltk graphical toolkit.
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
SMSConsole(1), SMSBatch(1), SMSTools(1)
