/*
 * Copyright (c) 2004 MUSIC TECHNOLOGY GROUP (MTG)
 *                         UNIVERSITAT POMPEU FABRA
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef Fl_Progress_hxx
#define Fl_Progress_hxx
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Box.H>
#include "Mutex.hxx"

class Fl_Progress 
{
public:
	Fl_Progress();
	Fl_Window *mWindow;
	Fl_Slider *mSlider;
	Fl_Box *mLabel;
	~Fl_Progress();
	static void s_timeout(void* ptr);
	void timeout(void);
	
	void  setValue( float newValue );
	float getValue( ) const;

protected:
	float              mValue;
	CLAM::Mutex        mValueGuard;
	static CLAM::Mutex smInstanceGuard;
};
#endif
