PROGRAMS=\
	SpectralDelay_FLTK\
	SpectralDelay_Console\

TOP=../..

INCLUDE_DIRS+= \
$(TOP)/examples/SpectralDelay/Processing \
$(TOP)/examples/SpectralDelay/App \
$(TOP)/examples/SpectralDelay/GUI \
$(TOP)/examples/SpectralDelay/GUI/Qt \
$(TOP)/examples/SpectralDelay/GUI/FLTK \
$(TOP)/examples/SpectralDelay/Util \
$(TOP)/examples/SpectralDelay/GUI/View \
$(TOP)/examples/SpectralDelay/GUI/Presentation 

include $(TOP)/unix_tools/make.rules






