PROGRAMS=Salto SaltoConsole

TOP=../..

INCLUDES += \
-I$(TOP)/examples/SALTOv2/Application \
-I$(TOP)/examples/SALTOv2/Application/MIDIIO \
-I$(TOP)/examples/SALTOv2/Base \
-I$(TOP)/examples/SALTOv2/Data \
-I$(TOP)/examples/SALTOv2/Defines \
-I$(TOP)/examples/SALTOv2/FileIO \
-I$(TOP)/examples/SALTOv2/GUI \
-I$(TOP)/examples/SALTOv2/Processing \
-I$(TOP)/examples/SALTOv2/Processing/SynthesisAudio \
-I$(TOP)/examples/SALTOv2/Processing/SynthesisControl \
-I$(TOP)/examples/SALTOv2/Storage \
-I$(TOP)/examples/SALTOv2/Storage/SDIF \

include $(TOP)/unix_tools/make.rules

