.TH SMSBatch 1 "August 24, 2005" "version 0.1.2" "User Commands"
.SH NAME
SMSBatch \- command line based interface to SMS analysis, synthesis and transformation
.SH SYNOPSIS
.B SMSBatch
.SH DESCRIPTION
Here goes SMSBatch description
.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
SMSTools(1), SMSConsole(1), QtSMSTools(1)
