.TH BOCACLIENT "1" "December 2008" "BocaClient" "User Commands"
.SH NAME
BocaClient \- Assembles Music Annotator projects from a BOCA task
.SH SYNOPSIS
.B BocaClient
[\fIoptions\fR] \fIaudiofile1 audiofile2 \fR...
.SH DESCRIPTION
BocaClient creates an CLAM Music Annotator project from a BOCA task definition,
by downloading all the needed descriptors and task state from Simac WebServices.
.SH "SEE ALSO"
Annotator(1)

