.TH CHORDEXTRACTOR "1" "December 2008" "ChordExtractor" "User Commands"
.SH NAME
ChordExtractor \- Detects starting notes in a wave file
.SH SYNOPSIS
.B ChordExtractor
[\fIoptions\fR] \fIaudiofile1 audiofile2 \fR...
.SH DESCRIPTION
ChordExtractor extracts tonal information from a wave file containing music
and exports it as CLAM Annotator XML format.
Tonal information includes the chord segmentation and instant pitch
class profile among others.
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-s\fR SCHEMAFILE, \fB\-\-print\-schema\fR=\fISCHEMAFILE\fR
Outputs the description schema for the extractor. Use
\&'\-' for standard output.
.TP
\fB\-w\fR, \fB\-\-writeback\fR
Writes back the descriptors to the source. (Not
applied in this extrator)
.TP
\fB\-f\fR SUFFIX, \fB\-\-suffix\fR=\fISUFFIX\fR
Appends SUFFIX to the generated descriptors file
(default: '.pool')
.TP
\fB\-c\fR CONFIGURATIONFILE, \fB\-\-configuration\fR=\fICONFIGURATIONFILE\fR
Specifies a configuration file with the options for
the extractor.
.SH "SEE ALSO"
Annotator(1), ClamExtractorExample(1), OnsetExtractor(1)

