import sys, os, string, glob

neted_env = Environment( tools=['default','qt'], ENV=os.environ )

neted_env.Replace(QT_LIB='qt-mt')

opts = Options('NetworkEditor.conf')
opts.Add( PathOption( 'clam_prefix', 'Prefix were CLAM was installed', '/usr') )
opts.Add( BoolOption( 'release', 'Build network editor enabling compiler optimizations', 'yes') )
opts.Update(neted_env)
opts.Save('NetworkEditor.conf', neted_env)
Help(opts.GenerateHelpText(neted_env))

if neted_env['release'] :
	neted_env.Append( CCFLAGS=['-O3','-fomit-frame-pointer','-Wall'] )
else :
	neted_env.Append( CCFLAGS=['-g', '-Wall'] )


neted_env.ParseConfig( 'pkg-config --cflags --libs clam_core clam_processing clam_audioio clam_vmqt clam_vmfl'  )

source_dirs = ['../src','../src/GUI','../src/GUI/Base','../src/GUI/Interface','../src/GUI/Qt_Presentations','../src/GUI/Qt_Presentations/ConcretePresentations', '../src/Processings','../src/Visualization']

neted_env.Append(CPPPATH=source_dirs)
neted_env.Append(CCFLAGS='-include CLAM/preinclude.hxx')
sourcefiles = []
for dir in source_dirs :
	sourcefiles += glob.glob(dir+'/*.cxx')
	sourcefiles += glob.glob(dir+'/*.ui')
neted_bin = neted_env.Program( 'NetworkEditor', sourcefiles, LINKFLAGS=['-rdynamic'] )
