.TH Turnaround 1 "August 24, 2005" "version 0.3.0" "MISCELLANEOUS"
.SH NAME
Turnaround \- Analyzes chords on audio files
.SH SYNOPSIS
.B Turnaround <wavefile>
.SH DESCRIPTION
.PP
CLAM Turnaround is a chord detection tool that can be used to
browse the chords of your favourite mp3/ogg/wav music.
You can freely move arround the song, listening and 
getting insight of its tonal features by using several
available views: Chord segments, Chord ranking, Tonnetz,
Keyspace, Chromatic peaks, PCPgram...
.
This is an example application of the CLAM framework.

.SH AUTHOR
CLAM development team (clam (at) iua.upf.es)
.SH SEE ALSO
Turnaround(1)
