// generated by Fast Light User Interface Designer (fluid) version 1.0103

#include "UserInterface.hxx"
#include "SMSAnalysisSynthesisConfig.hxx"

inline void UserInterface::cb_mLoadCfgMenuItem_i(Fl_Menu_*, void*) {
  LoadConfiguration();
}
void UserInterface::cb_mLoadCfgMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mLoadCfgMenuItem_i(o,v);
}

inline void UserInterface::cb_mEditCfgMenuItem_i(Fl_Menu_*, void*) {
  EditConfiguration();
}
void UserInterface::cb_mEditCfgMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mEditCfgMenuItem_i(o,v);
}

inline void UserInterface::cb_mStoreCfgMenuItem_i(Fl_Menu_*, void*) {
  StoreConfiguration();
}
void UserInterface::cb_mStoreCfgMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreCfgMenuItem_i(o,v);
}

inline void UserInterface::cb_mLoadAnalysisMenuItem_i(Fl_Menu_*, void*) {
  LoadAnalysisData();
}
void UserInterface::cb_mLoadAnalysisMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mLoadAnalysisMenuItem_i(o,v);
}

inline void UserInterface::cb_mStoreAnalysisMenuItem_i(Fl_Menu_*, void*) {
  StoreAnalysisData();
}
void UserInterface::cb_mStoreAnalysisMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreAnalysisMenuItem_i(o,v);
}

inline void UserInterface::cb_mStoreMelodyMenuItem_i(Fl_Menu_*, void*) {
  StoreMelody();
}
void UserInterface::cb_mStoreMelodyMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreMelodyMenuItem_i(o,v);
}

inline void UserInterface::cb_mLoadSMSTransScoreMenuItem_i(Fl_Menu_*, void*) {
  LoadTransformation();
}
void UserInterface::cb_mLoadSMSTransScoreMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mLoadSMSTransScoreMenuItem_i(o,v);
}

inline void UserInterface::cb_mEditSMSTransScoreMenuItem_i(Fl_Menu_*, void*) {
  EditTransformScore();
}
void UserInterface::cb_mEditSMSTransScoreMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mEditSMSTransScoreMenuItem_i(o,v);
}

inline void UserInterface::cb_mSaveSMSTransScoreMenuItem_i(Fl_Menu_*, void*) {
  SaveTransformScore();
}
void UserInterface::cb_mSaveSMSTransScoreMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mSaveSMSTransScoreMenuItem_i(o,v);
}

inline void UserInterface::cb_mStoreSMSSynthSoundMenuItem_i(Fl_Menu_*, void*) {
  StoreOutputSound();
}
void UserInterface::cb_mStoreSMSSynthSoundMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreSMSSynthSoundMenuItem_i(o,v);
}

inline void UserInterface::cb_mStoreSMSSynthSinusoidalMenuItem_i(Fl_Menu_*, void*) {
  StoreOutputSoundSinusoidal();
}
void UserInterface::cb_mStoreSMSSynthSinusoidalMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreSMSSynthSinusoidalMenuItem_i(o,v);
}

inline void UserInterface::cb_mStoreSMSSynthResidualMenuItem_i(Fl_Menu_*, void*) {
  StoreOutputSoundResidual();
}
void UserInterface::cb_mStoreSMSSynthResidualMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreSMSSynthResidualMenuItem_i(o,v);
}

inline void UserInterface::cb_mAppExitMenuItem_i(Fl_Menu_*, void*) {
  if(mWindow2!=NULL) delete mWindow2;
Exit();
}
void UserInterface::cb_mAppExitMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mAppExitMenuItem_i(o,v);
}

inline void UserInterface::cb_mDoSMSAnalysisMenuItem_i(Fl_Menu_*, void*) {
  Analyze();
}
void UserInterface::cb_mDoSMSAnalysisMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mDoSMSAnalysisMenuItem_i(o,v);
}

inline void UserInterface::cb_mMelodyExtractionMenuItem_i(Fl_Menu_*, void*) {
  AnalyzeMelody();
}
void UserInterface::cb_mMelodyExtractionMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mMelodyExtractionMenuItem_i(o,v);
}

inline void UserInterface::cb_mDoSMSTransMenuItem_i(Fl_Menu_*, void*) {
  Transform();
}
void UserInterface::cb_mDoSMSTransMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mDoSMSTransMenuItem_i(o,v);
}

inline void UserInterface::cb_mUndoTransMenuItem_i(Fl_Menu_*, void*) {
  UndoTransform();
}
void UserInterface::cb_mUndoTransMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mUndoTransMenuItem_i(o,v);
}

inline void UserInterface::cb_mDoSMSSynthesisMenuItem_i(Fl_Menu_*, void*) {
  Synthesize();
}
void UserInterface::cb_mDoSMSSynthesisMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mDoSMSSynthesisMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowOriginalAudioMenuItem_i(Fl_Menu_*, void*) {
  DisplayInputSound();
}
void UserInterface::cb_mShowOriginalAudioMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowOriginalAudioMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowSinTracksMenuItem_i(Fl_Menu_*, void*) {
  DisplaySinusoidalTracks();
}
void UserInterface::cb_mShowSinTracksMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSinTracksMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowFundFreqMenuItem_i(Fl_Menu_*, void*) {
  DisplayFundFreqTrajectory();
}
void UserInterface::cb_mShowFundFreqMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowFundFreqMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowSpectrumAndPeaksMenuItem_i(Fl_Menu_*, void*) {
  DisplaySpectrumAndPeaks();
}
void UserInterface::cb_mShowSpectrumAndPeaksMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSpectrumAndPeaksMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowSinusoidalSpectrumMenuItem_i(Fl_Menu_*, void*) {
  DisplaySinusoidalSpectrum();
}
void UserInterface::cb_mShowSinusoidalSpectrumMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSinusoidalSpectrumMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowResidualSpectrumMenuItem_i(Fl_Menu_*, void*) {
  DisplayResidualSpectrum();
}
void UserInterface::cb_mShowResidualSpectrumMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowResidualSpectrumMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowSynthesizedAudioMenuItem_i(Fl_Menu_*, void*) {
  DisplaySynthesizedAudio();
}
void UserInterface::cb_mShowSynthesizedAudioMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSynthesizedAudioMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowSynthesizedSinusoidalMenuItem_i(Fl_Menu_*, void*) {
  DisplaySynthesizedSinusoidal();
}
void UserInterface::cb_mShowSynthesizedSinusoidalMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSynthesizedSinusoidalMenuItem_i(o,v);
}

inline void UserInterface::cb_mShowSynthesizedResidualMenuItem_i(Fl_Menu_*, void*) {
  DisplaySynthesizedResidual();
}
void UserInterface::cb_mShowSynthesizedResidualMenuItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSynthesizedResidualMenuItem_i(o,v);
}

inline void UserInterface::cb_About_i(Fl_Menu_*, void*) {
  AboutWindow();
}
void UserInterface::cb_About(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_About_i(o,v);
}

Fl_Menu_Item UserInterface::menu_mMenuBar[] = {
 {"File", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Configuration", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Load", 0,  (Fl_Callback*)UserInterface::cb_mLoadCfgMenuItem, 0, 0, 0, 0, 12, 56},
 {"Edit", 0,  (Fl_Callback*)UserInterface::cb_mEditCfgMenuItem, 0, 0, 0, 0, 12, 56},
 {"Save", 0,  (Fl_Callback*)UserInterface::cb_mStoreCfgMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"SMS Analysis", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Load Analysis Data...", 0,  (Fl_Callback*)UserInterface::cb_mLoadAnalysisMenuItem, 0, 0, 0, 0, 12, 56},
 {"Store Analysis Data...", 0,  (Fl_Callback*)UserInterface::cb_mStoreAnalysisMenuItem, 0, 1, 0, 0, 12, 56},
 {0},
 {"Melody", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Save Extracted Melody...", 0,  (Fl_Callback*)UserInterface::cb_mStoreMelodyMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"SMS Transformation", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Load Score...", 0,  (Fl_Callback*)UserInterface::cb_mLoadSMSTransScoreMenuItem, 0, 0, 0, 0, 12, 56},
 {"Edit Score...", 0,  (Fl_Callback*)UserInterface::cb_mEditSMSTransScoreMenuItem, 0, 0, 0, 0, 12, 56},
 {"Save Score...", 0,  (Fl_Callback*)UserInterface::cb_mSaveSMSTransScoreMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"SMS Synthesis", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Save synthesized sound...", 0,  (Fl_Callback*)UserInterface::cb_mStoreSMSSynthSoundMenuItem, 0, 0, 0, 0, 12, 56},
 {"Save synthesized sinusoidal...", 0,  (Fl_Callback*)UserInterface::cb_mStoreSMSSynthSinusoidalMenuItem, 0, 0, 0, 0, 12, 56},
 {"Save synthesized residual...", 0,  (Fl_Callback*)UserInterface::cb_mStoreSMSSynthResidualMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"Exit", 0x40071,  (Fl_Callback*)UserInterface::cb_mAppExitMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"SMS Analysis", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Analyze", 0x40061,  (Fl_Callback*)UserInterface::cb_mDoSMSAnalysisMenuItem, 0, 1, 0, 0, 12, 56},
 {"Melody Extraction", 0,  (Fl_Callback*)UserInterface::cb_mMelodyExtractionMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"SMS Transformation", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Apply", 0,  (Fl_Callback*)UserInterface::cb_mDoSMSTransMenuItem, 0, 1, 0, 0, 12, 56},
 {"Undo Transformation", 0,  (Fl_Callback*)UserInterface::cb_mUndoTransMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"SMS Synthesis", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Synthesize", 0x40073,  (Fl_Callback*)UserInterface::cb_mDoSMSSynthesisMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {"View", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Original Audio", 0,  (Fl_Callback*)UserInterface::cb_mShowOriginalAudioMenuItem, 0, 0, 0, 0, 12, 56},
 {"Analysis Results", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Sinusoidal Tracks", 0,  (Fl_Callback*)UserInterface::cb_mShowSinTracksMenuItem, 0, 0, 0, 0, 12, 56},
 {"Fundamental Frequency", 0,  (Fl_Callback*)UserInterface::cb_mShowFundFreqMenuItem, 0, 0, 0, 0, 12, 56},
 {"Frame Data", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Spectrum and Peaks", 0,  (Fl_Callback*)UserInterface::cb_mShowSpectrumAndPeaksMenuItem, 0, 0, 0, 0, 12, 56},
 {"Sinusoidal Spectrum", 0,  (Fl_Callback*)UserInterface::cb_mShowSinusoidalSpectrumMenuItem, 0, 1, 0, 0, 12, 56},
 {"Residual Spectrum", 0,  (Fl_Callback*)UserInterface::cb_mShowResidualSpectrumMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {0},
 {"Synthesis Results", 0,  0, 0, 64, 0, 0, 12, 56},
 {"Synthesized Audio", 0,  (Fl_Callback*)UserInterface::cb_mShowSynthesizedAudioMenuItem, 0, 0, 0, 0, 12, 56},
 {"Synthesized Sinusoidal", 0,  (Fl_Callback*)UserInterface::cb_mShowSynthesizedSinusoidalMenuItem, 0, 0, 0, 0, 12, 56},
 {"Synthesized Residual Sound", 0,  (Fl_Callback*)UserInterface::cb_mShowSynthesizedResidualMenuItem, 0, 0, 0, 0, 12, 56},
 {0},
 {0},
 {"Help", 0,  0, 0, 64, 0, 0, 12, 56},
 {"About", 0,  (Fl_Callback*)UserInterface::cb_About, 0, 0, 0, 0, 12, 56},
 {0},
 {0}
};
Fl_Menu_Item* UserInterface::mFileMenuItem = UserInterface::menu_mMenuBar + 0;
Fl_Menu_Item* UserInterface::mConfigurationOpsMenuItem = UserInterface::menu_mMenuBar + 1;
Fl_Menu_Item* UserInterface::mLoadCfgMenuItem = UserInterface::menu_mMenuBar + 2;
Fl_Menu_Item* UserInterface::mEditCfgMenuItem = UserInterface::menu_mMenuBar + 3;
Fl_Menu_Item* UserInterface::mStoreCfgMenuItem = UserInterface::menu_mMenuBar + 4;
Fl_Menu_Item* UserInterface::mAnalysisFileOpsMenuItem = UserInterface::menu_mMenuBar + 6;
Fl_Menu_Item* UserInterface::mLoadAnalysisMenuItem = UserInterface::menu_mMenuBar + 7;
Fl_Menu_Item* UserInterface::mStoreAnalysisMenuItem = UserInterface::menu_mMenuBar + 8;
Fl_Menu_Item* UserInterface::mMelodyFileOpsMenuItem = UserInterface::menu_mMenuBar + 10;
Fl_Menu_Item* UserInterface::mStoreMelodyMenuItem = UserInterface::menu_mMenuBar + 11;
Fl_Menu_Item* UserInterface::mSMSTransFileOpsMenuItem = UserInterface::menu_mMenuBar + 13;
Fl_Menu_Item* UserInterface::mLoadSMSTransScoreMenuItem = UserInterface::menu_mMenuBar + 14;
Fl_Menu_Item* UserInterface::mEditSMSTransScoreMenuItem = UserInterface::menu_mMenuBar + 15;
Fl_Menu_Item* UserInterface::mSaveSMSTransScoreMenuItem = UserInterface::menu_mMenuBar + 16;
Fl_Menu_Item* UserInterface::mSMSSynthesisFileOpsMenuItem = UserInterface::menu_mMenuBar + 18;
Fl_Menu_Item* UserInterface::mStoreSMSSynthSoundMenuItem = UserInterface::menu_mMenuBar + 19;
Fl_Menu_Item* UserInterface::mStoreSMSSynthSinusoidalMenuItem = UserInterface::menu_mMenuBar + 20;
Fl_Menu_Item* UserInterface::mStoreSMSSynthResidualMenuItem = UserInterface::menu_mMenuBar + 21;
Fl_Menu_Item* UserInterface::mAppExitMenuItem = UserInterface::menu_mMenuBar + 23;
Fl_Menu_Item* UserInterface::mSMSAnalysisMenuItem = UserInterface::menu_mMenuBar + 25;
Fl_Menu_Item* UserInterface::mDoSMSAnalysisMenuItem = UserInterface::menu_mMenuBar + 26;
Fl_Menu_Item* UserInterface::mMelodyExtractionMenuItem = UserInterface::menu_mMenuBar + 27;
Fl_Menu_Item* UserInterface::mSMSTransformationMenuItem = UserInterface::menu_mMenuBar + 29;
Fl_Menu_Item* UserInterface::mDoSMSTransMenuItem = UserInterface::menu_mMenuBar + 30;
Fl_Menu_Item* UserInterface::mUndoTransMenuItem = UserInterface::menu_mMenuBar + 31;
Fl_Menu_Item* UserInterface::mSMSSynthesisMenuItem = UserInterface::menu_mMenuBar + 33;
Fl_Menu_Item* UserInterface::mDoSMSSynthesisMenuItem = UserInterface::menu_mMenuBar + 34;
Fl_Menu_Item* UserInterface::mViewMenuItem = UserInterface::menu_mMenuBar + 36;
Fl_Menu_Item* UserInterface::mShowOriginalAudioMenuItem = UserInterface::menu_mMenuBar + 37;
Fl_Menu_Item* UserInterface::mShowAnalysisResultsMenuItem = UserInterface::menu_mMenuBar + 38;
Fl_Menu_Item* UserInterface::mShowSinTracksMenuItem = UserInterface::menu_mMenuBar + 39;
Fl_Menu_Item* UserInterface::mShowFundFreqMenuItem = UserInterface::menu_mMenuBar + 40;
Fl_Menu_Item* UserInterface::mViewFrameDataMenuItem = UserInterface::menu_mMenuBar + 41;
Fl_Menu_Item* UserInterface::mShowSpectrumAndPeaksMenuItem = UserInterface::menu_mMenuBar + 42;
Fl_Menu_Item* UserInterface::mShowSinusoidalSpectrumMenuItem = UserInterface::menu_mMenuBar + 43;
Fl_Menu_Item* UserInterface::mShowResidualSpectrumMenuItem = UserInterface::menu_mMenuBar + 44;
Fl_Menu_Item* UserInterface::mViewSynthesisResultsMenuItem = UserInterface::menu_mMenuBar + 47;
Fl_Menu_Item* UserInterface::mShowSynthesizedAudioMenuItem = UserInterface::menu_mMenuBar + 48;
Fl_Menu_Item* UserInterface::mShowSynthesizedSinusoidalMenuItem = UserInterface::menu_mMenuBar + 49;
Fl_Menu_Item* UserInterface::mShowSynthesizedResidualMenuItem = UserInterface::menu_mMenuBar + 50;
Fl_Menu_Item* UserInterface::mHelpMenuItem = UserInterface::menu_mMenuBar + 53;

inline void UserInterface::cb_mCounter_i(Fl_Counter*, void*) {
  ChangeFrame();
}
void UserInterface::cb_mCounter(Fl_Counter* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mCounter_i(o,v);
}

inline void UserInterface::cb_mWindow2_i(Fl_Double_Window*, void*) {
  delete mWindow2;
mWindow2=NULL;
}
void UserInterface::cb_mWindow2(Fl_Double_Window* o, void* v) {
  ((UserInterface*)(o->user_data()))->cb_mWindow2_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_iua2[] = {
"100 98 21 1",
" \tc None",
".\tc #0236FE",
"+\tc #FEFEFE",
"@\tc #FCF1F5",
"#\tc #F2CAD9",
"$\tc #073BFE",
"%\tc #7794FE",
"&\tc #5479FE",
"*\tc #3460FE",
"=\tc #1244FE",
"-\tc #2352FE",
";\tc #FF0000",
">\tc #1647FE",
",\tc #E6557A",
"\'\tc #1A4AFE",
")\tc #3C64FE",
"!\tc #F23654",
"~\tc #E9819F",
"{\tc #EB6887",
"]\tc #F44461",
"^\tc #F19FB4",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!,^##^~{!;;];;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!~##^{!!;;;]~];;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!#^{;;;;!]~^^!!;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!^,!,{~~^^^{,{^{;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!;;!!!!!!]~^#^,!;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;{~~~{{{~^,;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!~~,;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;{@^;;;;{@^;;;;;;;;\
;;;;;;;;;!#;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;{+^;;;;~+^;;;;;;;;\
;;;;;;;;;~+{;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,#{;;;;;;;;;;;;;;;;{+#;;;;~+^;;;;;;;;\
;;;;;;;;!###;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~+^;;;;;;;;;;;;;;;~~+^;;;;~+^~!;;;;;;\
;;;;;;;;{#]@{;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;{!;;;;;;;;;;;;;;;^~+^;;;;~+^~];;;;;;\
;;;;;;;;#^;^#;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!#{;;;;;;;;;;;;;;;;{+^;;;;~+^;;;;;;;;\
;;;;;;;,@];!@,;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!@~;;;;;;;;;;;;;;;;,+^;;;;~+~;;;;;;;;\
;;;;;;;^#;;;^#;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!@~;;;;;;;;;;;;;;;;,+#!;;;~+~;;;;;;;;\
;;;;;;]@^!!]~@,;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!@~;;;;;;;;;;;;;;;;,++^;;;#+~;;;;;;;;\
;;;;;;^+@#@@++^;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!@~;;;;;;;;;;;;;;;;~+++##@++^!!!;;;;;\
;;;;;!@~!!!!]^@];;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!@~;;;;;;;;;;;;;;{#++++++++++@@@#^^^^\
~{]]{^@!;;;;;]@^;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!@~;;;;;;;;;;;!{#@+++++++++++++++++++\
++@@@@@~!;;;;;^#!;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!#~;;;;;;;;!^#@++++++++++++++++++++++\
++++++++#{;;;;;!;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!;;;;;;;;~@+++++++++++++++++++++++++\
+++++++++@^!;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;]#+++++++++++++@@##@@++++++++\
+++++++++++@,;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~@++++++++++@@^~]!;;!]^#^^^^##\
##@@@@++++++@~;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~+++++++++#^{]!;;;;;;;;;;;;;;;;\
;;!]]{#@+++++@!;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~+++++++##^!;;;;;;;;;;;;;;;;;;;;\
;;;;;;;!{#@+++^;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~+++++@#~;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;,@++@,;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~++++@~!;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;]@@+^;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~+++@^];;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;!,~,;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~++#~!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#@~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;]!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;!{^######^];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;]^@+++++++++@^;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;{@+++++++++++++#!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;{@+++++@@^^#@@+++#!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;]@++++#^!!;;;!!{@++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;#++++^!;;;;;;;;;!#++~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;]@+++^;;;;;;;;;;;;{++@!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;]#+++^;;;;;;;;;;;;;!@++~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;]@+++@!;;;;;;;;;;;;;;#++^;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!!!~#^###^~!!;!;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;^++++~;;;;;;;;;;;;;;;#++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!~^#@@@++++++++@@#@#\
~,!;;;;;;;;;;;;;;;;;;;;",
";;;~+++#;;;;;;;;;;;;;;;!@++#!;;;;;;;;;;;;;;;;;;;;;;;;;;~#++++++@####%####@@@+\
++@#{;;;;;;;;;;;;;;;;;;",
";;;^+++^;;;;;;;;;;;;;;;~+++#;;;;;;;;;;;;;;;;;;;;;;;;]~#+++++++#*$$.$$$.$=\'\'\
)%#@+++@,;;;;;;;;;;;;;;;;",
";;;^+++,;;;;;;;;;;;;;;,@+++~;;;;;;;;;;;;;;;;;;;;;!^@+++++++++%\'.............\
.$&@#@+@{;;;;;;;;;;;;;;;",
";;;^+++~;;;;;;;;;;;;;{@+++#;;;;;;;;;;;;;;;;;;;;;{@++++++++++#>...............\
.$=\'%++@~;;;;;;;;;;;;;;",
";;;~+++#;;;;;;;]~^^##++++@];;;;;;;;;;;;;;;;;;;]#++++@@+++++@*................\
...$*@+++#!;;;;;;;;;;;;",
";;;]@+++{;;;;;^@++++++++@];;;;;;;;;;;;;;;;;;,^@+++#{!,+++++%=........>%%&&=..\
....$#++++^;;;;;;;;;;;;",
";;;!#+++#;;;;;]#+++++++^!;;;;;;;;;;;;;;;;;;~@++@#{;;;!@++++*........$%++++#).\
....$%++++@;;;;;;;;;;;;",
";;;;^+++@];;;;;!{^#@@#{;;;;;;;;;;;;;;;;;;!^@+@^];;;;;]@++++)........&@+++++#$\
....$%++++^;;;;;;;;;;;;",
";;;;,++++~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#++@{;;;;;;;{+++++).......\'@++++++@\
&.....&+++#!;;;;!;;;;;;;",
";;;;!#+++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,++#!;;;;;;;;{+++++).......-@+++++++%\
$....&+++~;;;;^@];;;;;;",
";;;;;^+++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,@^!;;;;;;;;;~+++++&.......=#+++++++%\
....$&++@];;;;#+^;;;;;;",
";;;;;]@++@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!!;;;;;;;;;;;~+++++&........&++++++#\
\'.....&++@!;;;;#+@,;;;;;",
";;;;;;#++@];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~+++++%$.......=#++++@&.\
.....%++@!;;;!@++^;;;;;",
";;;;;;^+++{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!~;;;;;;;;;{+++++#$........-%@+@&$.\
....$%++@!;;;~+++~;;;;;",
";;;;;;{+++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;]+^,;;;;;;;!@++++@-.........$-*-...\
....$%+++~!]#+++#!;;;;;",
";;;;;;!@++@];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#++#];;;;;;#+++++%$...............\
...$-@++++@@+++#!;;;;;;",
";;;;;;!@+++^;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~@+@{;;;;;^+++++@-...............\
..$&#++++++++@^!;;;;;;;",
";;;;;;!@+++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;]^+@^];;;^++++++%-..............\
$\'%@+++++++@~!;;;;;;;;;",
";;;;;;;#+++@!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~@+@{;!#+++++++#)$.........$*&\
##+++++++@^];;;;;;;;;;;",
";;;;;;;#+++@!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~@+@#@+++++++++@&\'\'>>=--&%%\
@+++++++++@~;;;;;;;;;;;;;",
";;;;;;;#+++@,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;]^+++++++++++++@@####@@+++++\
++++++@#,;;;;;;;;;;;;;;",
";;;;;;;^+++@,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;{#@+++++++++++++++++++++++\
++++@^!;;;;;;;;;;;;;;;;",
";;;;;;;#+++@];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!{^@@+++++++++++++++++++\
+@@#];;;;;;;;;;;;;;;;;;",
";;;;;;!@+++@!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;]{~#@@+++++++++++++@\
~!;;;;;;;;;;;;;;;;;;;;;",
";;;;;;!@+++@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;!{~###@##@@^{,!\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;]++++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;];;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;~++++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;~++++^;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;]@+++~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;!@+++{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;#+++{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;^+++,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;^+++{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;^+++{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;~+++{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;~+++~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;~+++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;{+++@!;;;;;;;;;;;;;{#^!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;!++++{;;;;;;;;;;;;;^++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;!@+++#;;;;;;;;;;;;!@++#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;~@+++{;;;;;;;;;;;^++@{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;{@++@];;;;;;;;;,@++^;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;]#++@~,;;;;;,{#++^;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;!@++++@#~{^@++@~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;]#@#@+++++++#,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;!!;!~#@+@#{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;]{!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\
;;;;;;;;;;;;;;;;;;;;;;;"
};
static Fl_Pixmap image_iua2(idata_iua2);

static const char *idata_mtg3[] = {
"100 98 21 1",
" \tc None",
".\tc #EA1A1E",
"+\tc #EA2628",
"@\tc #625E8E",
"#\tc #F27D7E",
"$\tc #8E8AAE",
"%\tc #B3B1BA",
"&\tc #BEBEBE",
"*\tc #D0C8CA",
"=\tc #DDD2D2",
"-\tc #F2686B",
";\tc #E6DCDC",
">\tc #EE6162",
",\tc #F0E4E4",
"\'\tc #EE5354",
")\tc #F0EAEA",
"!\tc #F28A8B",
"~\tc #EFA6A7",
"{\tc #ED3F41",
"]\tc #FEFEFE",
"^\tc #FABEBE",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]~\',]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]~+..,]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]#...,]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]#...,]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]#...,]]]]]]\
]]]]]]]]]]]]]]]]]]]~]]]",
"]]]%$$$$$$$$$$$$$$$$$$$$$$$*]]^~^]]];!->-!;]]]]]^#>>#^]]]]]]]]]]^~>...~~~~~^]\
]]]]]]]]])~->>#~)]#.#]]",
"]]]$@@@@@@@@@@@@@@@@@@@@@@@%]]{.+)]#.......-)]^{......{^]]]]]]]]+..........\'\
]]]]]]]]]!+......+>...!]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..#\'.........{~.........+=]]]]]]]+..........\
\']]]]]]]]\'............#]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{.....>~~#+......+#~~-+...{]]]]]]]!!\'...#!!!!~\
]]]]]]]-...+!^^!+...{]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{...+^]]]]]\'....\',]]]];+...^]]]]]]]]#...,]]]]\
]]]]]]]^...+;]]]];+...^]]",
"]]]%$$$$$$$$$$$$$$$$$$$$$$$*]]{...^]]]]]],...+)]]]]]]!...!]]]]]]]]#...,]]]]]]\
]]]]]-...~]]]]]]~...>]]",
"]]]$@@@@@@@@@@@@@@@@@@@@@@@%]]{..{]]]]]]]]+..\']]]]]]];...-]]]]]]]]#...,]]]]]\
]]]]]]{..+]]]]]]]]+..{]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]];...-]]]]]]]]#...,]]]]]\
]]]]]]{..+]]]]]]]]+..{]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]])...-]]]]]]]]#...,]]]]]\
]]]]]]+..{]]]]]]]]{..+]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]#...,]]]]]\
]]]]]]+..{]]]]]]]]{..+]]",
"]]]%$$$$$$$$$$$$$$$$$$$$$$$*]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]#...,]]]]]\
]]]]]]\'..+)]]]]]])+..{]]",
"]]]$@@@@@@@@@@@@@@@@@@@@@@@%]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]#...,]]]]]\
]]]]]]!...!]]]]]]~...#]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]#...,]]]]]\
]]]]]],+..+^]]]];+...;]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]#...,]]]]]\
]]]]]]]!....-~~#+...#]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]#...,]]]]]\
]]]]]]]]!..........-]]]]",
"]]]%$$$$$$$$$$$$$$$$$$$$$$$*]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]#...;]]]]]\
]]]]]]]]]^+......{~]]]]]",
"]]]$@@@@@@@@@@@@@@@@@@@@@@@%]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]!...^]]]]]\
]]]]]]]]!+.+\'-#~=]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]~...#]]]]]\
]]]]]]]>.+^]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]],....^]]]]\
;]]]]],..{;);^!#>-!^]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]]-....{>\'\
+{]]]]]).............{;]]",
"]]]%$$$$$$$$$$$$$$$$$$$$$$$*]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]]){.......\
+]]]]]]>.............+,]",
"]]]$@@@@@@@@@@@@@@@@@@@@@@@%]]{..{]]]]]]]]+..\']]]]]]]]...-]]]]]]]]]])-......\
+,]]]]]]!{+.+\'#~~#+...-]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],^~^^,]\
]]]]]]]]]]]]]]]]]){..+]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]!...)",
"]]]]]]]]]]]]]]]]=)]]]]]],]]]]]]]]])*]]]]]]]]]])*]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]],]]]]]]]]]]-...)",
"]]];*;*;];],];*]*]]**]]]%&])*;])*=)&*)];*)];*))*],*)];*;;]];]]]**);=,)*;];];]\
=*;]]]^+-,]]]]]]]~...\']",
"]]]%)%)&]&]*)%)]*)&))]]]*)]&)*;%)))&)&)&)&)&]%)*]%]%)&)*=,;;]]*)&)%)]%]&)&]&]\
%]&)]]{...\'~^^^!\'....^]",
"]]]&]&]*)&]*)=&]*)%]]]]]*)]%*&;&]])*]&)*]%;;]%)*)*]&,&;*]*&]]]*;&)&])&]*,&]&]\
&]=,]~..............!]]",
"]]]&]&]*)&]&))=;*)&))]]]*,]%])]%]))*]&)*]%)*]%)&]&]%]&*]]&&]]];&;]&]]%]&)%]%]\
&]&)]]^\'..........{^]]]",
"]]];]=];];&=]**];])**]]]]&,)&*])&*);]=];]=]=*)]*];&,]**&]*;]]])*&;=]],&;];**]\
%&;]]]]],!>{+.+{#^]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]&**)&]]]];*&,]]]]]]]]]]]\
&]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])]]]]]]]])]]]]]]]]]]]]]\
)]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]",
"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\
]]]]]]]]]]]]]]]]]]]]]]]"
};
static Fl_Pixmap image_mtg3(idata_mtg3);

UserInterface::UserInterface() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mWindow = new Fl_Double_Window(870, 550, "SMS Tools 2 | MTG-UPF (Barcelona)");
    w = o;
    o->user_data((void*)(this));
    { Fl_Menu_Bar* o = mMenuBar = new Fl_Menu_Bar(0, 0, 872, 25);
      o->labelsize(13);
      o->textsize(12);
      o->menu(menu_mMenuBar);
    }
    { Fl_Group* o = new Fl_Group(0, 520, 870, 30);
      { Fl_Counter* o = mCounter = new Fl_Counter(340, 525, 190, 20, "Frame ");
        o->labelsize(12);
        o->minimum(0);
        o->maximum(0);
        o->step(1);
        o->callback((Fl_Callback*)cb_mCounter);
        o->align(FL_ALIGN_LEFT);
        o->deactivate();
      }
      { Fl_Box* o = new Fl_Box(0, 520, 340, 30);
        Fl_Group::current()->resizable(o);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(0, 25, 870, 495);
      { Fl_Smart_Tile* o = mSmartTile = new Fl_Smart_Tile(0, 30, 870, 490);
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        Fl_Group::current()->resizable(o);
        o->minsize(80);
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    mWindow2=NULL;
    o->end();
  }
}

void UserInterface::AboutWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mWindow2 = new Fl_Double_Window(450, 180, "About this program...");
    w = o;
    o->labelsize(10);
    o->callback((Fl_Callback*)cb_mWindow2, (void*)(this));
    { Fl_Box* o = new Fl_Box(5, 5, 440, 30, "SMS Tools 2");
      o->box(FL_FLAT_BOX);
      o->labelfont(1);
      o->labelsize(16);
      o->labelcolor(0);
    }
    new Fl_Box(110, 45, 230, 25, "MTG - IUA - UPF");
    { Fl_Box* o = new Fl_Box(345, 40, 100, 100);
      o->image(image_iua2);
    }
    new Fl_Box(110, 75, 230, 20, "Please visit us at");
    { Fl_Box* o = new Fl_Box(5, 40, 100, 100);
      o->image(image_mtg3);
    }
    { Fl_Box* o = new Fl_Box(110, 95, 230, 20, "http://www.iua.upf.es/mtg/");
      o->labelfont(4);
      o->labelcolor(4);
    }
    new Fl_Box(110, 115, 230, 20, "for more information");
    { Fl_Box* o = new Fl_Box(5, 145, 440, 30, "CLAM Release 0.5 beta 3");
      o->box(FL_FLAT_BOX);
      o->labelfont(3);
      o->labelcolor(0);
    }
    mWindow2->position(mWindow->x()+(mWindow->w()-mWindow2->w())/2,mWindow->y()+(mWindow->h()-mWindow2->h())/2);
    mWindow2->show();
    o->set_modal();
    o->end();
  }
}
