// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef UserInterface_hxx
#define UserInterface_hxx
#include <FL/Fl.H>
class Fl_Smart_Tile;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>

class UserInterface {
public:
  public: class AnalysisSynthesisExampleGUI* mAnalysisSynthesisExample;
  UserInterface();
  Fl_Double_Window *mWindow;
private:
  Fl_Input *mConfigurationText;
  Fl_Menu_Bar *mMenuBar;
  static Fl_Menu_Item menu_mMenuBar[];
  static Fl_Menu_Item *mSubMenu_1;
  static Fl_Menu_Item *mMenuItem_1_1;
  inline void cb_mMenuItem_1_1_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_1_1(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem_1_2;
  inline void cb_mMenuItem_1_2_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_1_2(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_2;
  static Fl_Menu_Item *mMenuItem_2;
  inline void cb_mMenuItem_2_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_2(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_2_1;
  static Fl_Menu_Item *mMenuItem_2_1;
  inline void cb_mMenuItem_2_1_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_2_1(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_3;
  static Fl_Menu_Item *mMenuItem_3_1;
  inline void cb_mMenuItem_3_1_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_3_1(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem_3_2;
  inline void cb_mMenuItem_3_2_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_3_2(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_4;
  static Fl_Menu_Item *mMenuItem_4;
  inline void cb_mMenuItem_4_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_4(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_4_1;
  static Fl_Menu_Item *mMenuItem_4_1;
  inline void cb_mMenuItem_4_1_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_4_1(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem_4_2;
  inline void cb_mMenuItem_4_2_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_4_2(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_4_2;
  static Fl_Menu_Item *mMenuItem_4_3;
  inline void cb_mMenuItem_4_3_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_4_3(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem_4_4;
  inline void cb_mMenuItem_4_4_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_4_4(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_4_3;
  static Fl_Menu_Item *mMenuItem_4_5;
  inline void cb_mMenuItem_4_5_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_4_5(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem_4_6;
  inline void cb_mMenuItem_4_6_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_4_6(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_5;
  static Fl_Menu_Item *mMenuItem_5_1;
  inline void cb_mMenuItem_5_1_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_5_1(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem_5_2;
  inline void cb_mMenuItem_5_2_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_5_2(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSubMenu_6;
  static Fl_Menu_Item *mMenuItem_6_1;
  inline void cb_mMenuItem_6_1_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_6_1(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem_6_2;
  inline void cb_mMenuItem_6_2_i(Fl_Menu_*, void*);
  static void cb_mMenuItem_6_2(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMenuItem;
  inline void cb_mMenuItem_i(Fl_Menu_*, void*);
  static void cb_mMenuItem(Fl_Menu_*, void*);
  Fl_Smart_Tile *mSmartTile;
  void AboutWindow();
  Fl_Window *mWindow2;
  inline void cb_mWindow2_i(Fl_Window*, void*);
  static void cb_mWindow2(Fl_Window*, void*);
  void LoadConfiguration(void);
  void DisplayInputSound(void);
  void Analyze(void);
  void LoadAnalysisData(void);
  void StoreAnalysisData(void);
  void Synthesize(void);
  void AnalyzeMelody(void);
  void StoreMelody(void);
  void StoreOutputSound(void);
  void DisplayOutputSound(void);
  void StoreOutputSoundResidual(void);
  void DisplayOutputSoundResidual(void);
  void StoreOutputSoundSinusoidal(void);
  void DisplayOutputSoundSinusoidal(void);
  void LoadTransformation(void);
  void Transform(void);
  void Exit(void);
};
#endif
